{
  parserClass="com.reason.parser.ReasonMLParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="ReasonML"
  psiImplClassSuffix="Impl"
  psiPackage="com.reason.psi"
  psiImplPackage="com.reason.psi.impl"

  elementTypeHolderClass="com.reason.psi.ReasonMLTypes"
  elementTypeClass="com.reason.psi.ReasonMLElementType"
  tokenTypeClass="com.reason.psi.ReasonMLTokenType"

  psiImplUtilClass="com.reason.psi.impl.ReasonMLPsiImplUtil"
}

reasonFile ::=
    ( COMMENT | module_statement | let_binding | fun_call )*

module_statement ::=
    MODULE module_ident EQUAL LBRACE module_body RBRACE SEMI { methods=[getPresentation] }

module_ident ::=
    UIDENT

module_body ::=
    (  module_statement
    | include_statement
    | type_statement
    | let_binding )*

include_statement ::=
    INCLUDE fqn SEMI

type_statement ::=
    TYPE SEMI

fun_call ::=
    fun_name (unit|seq_expr) SEMI

fun_name ::=
    LIDENT

unit ::=
    LPAREN RPAREN

let_binding ::=
    LET let_label let_binding_body SEMI  { methods=[getPresentation] }

let_label ::=
    LIDENT

let_binding_body ::=
    EQUAL fun_binding
  | EQUAL seq_expr

fun_binding ::=
    FUN LPAREN RPAREN ARROW seq_expr

seq_expr ::=
      LIDENT
    | tuple_expr
    | STRING

tuple_expr ::=
    LPAREN tuple_arg (COMMA tuple_arg)* RPAREN

tuple_arg ::=
    tuple_value (COLON core_type)?

tuple_value ::=
      INT
    | LIDENT

core_type ::=
  LIDENT

fqn ::=
    UIDENT (DOT UIDENT)*